export const RolePermissionCode = {
  // 성공 응답
  ASSIGN_SUCCESS: 'ROLE_PERMISSION_001',
  REVOKE_SUCCESS: 'ROLE_PERMISSION_002',
  ASSIGN_MULTIPLE_SUCCESS: 'ROLE_PERMISSION_003',
  REVOKE_MULTIPLE_SUCCESS: 'ROLE_PERMISSION_004',
  REPLACE_SUCCESS: 'ROLE_PERMISSION_005',
  FETCH_SUCCESS: 'ROLE_PERMISSION_006',

  // 에러 응답
  ASSIGN_ERROR: 'ROLE_PERMISSION_ERR_001',
  REVOKE_ERROR: 'ROLE_PERMISSION_ERR_002',
  ASSIGN_MULTIPLE_ERROR: 'ROLE_PERMISSION_ERR_003',
  REVOKE_MULTIPLE_ERROR: 'ROLE_PERMISSION_ERR_004',
  REPLACE_ERROR: 'ROLE_PERMISSION_ERR_005',
  FETCH_ERROR: 'ROLE_PERMISSION_ERR_006',
  ALREADY_ASSIGNED: 'ROLE_PERMISSION_ERR_007',
  NOT_ASSIGNED: 'ROLE_PERMISSION_ERR_008',
  INVALID_ROLE: 'ROLE_PERMISSION_ERR_009',
  INVALID_PERMISSION: 'ROLE_PERMISSION_ERR_010',
} as const;

export type RolePermissionCodeType = typeof RolePermissionCode[keyof typeof RolePermissionCode];