export const RolePermissionCode = {
  // 성공 응답
  ASSIGN_SUCCESS: 'ROLE_PERMISSION_001',
  REVOKE_SUCCESS: 'ROLE_PERMISSION_002',
  ASSIGN_MULTIPLE_SUCCESS: 'ROLE_PERMISSION_003',
  REVOKE_MULTIPLE_SUCCESS: 'ROLE_PERMISSION_004',
  REPLACE_SUCCESS: 'ROLE_PERMISSION_005',
  FETCH_SUCCESS: 'ROLE_PERMISSION_006',

  // 서버 에러 (000-099)
  ASSIGN_ERROR: 'ROLE_PERMISSION_ERR_001',
  REVOKE_ERROR: 'ROLE_PERMISSION_ERR_002',
  ASSIGN_MULTIPLE_ERROR: 'ROLE_PERMISSION_ERR_003',
  REVOKE_MULTIPLE_ERROR: 'ROLE_PERMISSION_ERR_004',
  REPLACE_ERROR: 'ROLE_PERMISSION_ERR_005',
  FETCH_ERROR: 'ROLE_PERMISSION_ERR_006',

  // 관계 조회 에러 (100-199)
  ROLE_PERMISSION_NOT_FOUND: 'ROLE_PERMISSION_ERR_101',
  ROLE_NOT_FOUND: 'ROLE_PERMISSION_ERR_102',
  PERMISSION_NOT_FOUND: 'ROLE_PERMISSION_ERR_103',

  // 관계 할당 에러 (200-299)
  ROLE_PERMISSION_ALREADY_EXISTS: 'ROLE_PERMISSION_ERR_201',
  INVALID_ROLE_PERMISSION_RELATION: 'ROLE_PERMISSION_ERR_202',

  // 배치 처리 에러 (300-399)
  BULK_OPERATION_PARTIAL_FAILURE: 'ROLE_PERMISSION_ERR_301',
  BULK_OPERATION_VALIDATION_FAILED: 'ROLE_PERMISSION_ERR_302',
} as const;

export type RolePermissionCodeType = typeof RolePermissionCode[keyof typeof RolePermissionCode];