services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio
    ports:
      - '4873:4873'
    volumes:
      - ./data/verdaccio/storage:/verdaccio/storage # 패키지, tarball 저장소
      - ./data/verdaccio/conf:/verdaccio/conf # 설정 파일 (config.yaml 등)
      - ./data/verdaccio/plugins:/verdaccio/plugins # 사용자 플러그인
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
    external: true
