export const AuthorizationCode = {
  // 성공 응답
  CHECK_PERMISSION_SUCCESS: 'AUTHORIZATION_001',
  CHECK_ROLE_SUCCESS: 'AUTHORIZATION_002',
  GET_USER_PERMISSIONS_SUCCESS: 'AUTHORIZATION_003',
  GET_USER_ROLES_SUCCESS: 'AUTHORIZATION_004',

  // 권한 관련 에러 (100-199)
  PERMISSION_DENIED: 'AUTHORIZATION_ERR_101',
  ROLE_ACCESS_DENIED: 'AUTHORIZATION_ERR_102',
  USER_NOT_AUTHENTICATED: 'AUTHORIZATION_ERR_103',
  
  // 서비스 관련 에러 (200-299)
  SERVICE_UNAVAILABLE: 'AUTHORIZATION_ERR_201',
  AUTHORIZATION_NETWORK_ERROR: 'AUTHORIZATION_ERR_202',
  AUTHORIZATION_TIMEOUT_ERROR: 'AUTHORIZATION_ERR_203',
} as const;

export type AuthorizationCodeType = typeof AuthorizationCode[keyof typeof AuthorizationCode];