export const PermissionCode = {
  // 000 ~ 099: 에러 코드
  PERMISSION_FETCH_ERROR: 'PERMISSION_000',
  PERMISSION_CREATE_ERROR: 'PERMISSION_001',
  PERMISSION_UPDATE_ERROR: 'PERMISSION_002',
  PERMISSION_DELETE_ERROR: 'PERMISSION_003',

  // 100 ~ 199: 에러 코드
  PERMISSION_NOT_FOUND: 'PERMISSION_100',
  PERMISSION_ALREADY_EXISTS: 'PERMISSION_101',
  PERMISSION_INVALID_ACTION: 'PERMISSION_102',
  PERMISSION_INVALID_SERVICE: 'PERMISSION_103',

  // 200 ~ 299: 성공 응답 코드
  PERMISSION_FETCH_SUCCESS: 'PERMISSION_200',
  PERMISSION_CREATE_SUCCESS: 'PERMISSION_201',
  PERMISSION_UPDATE_SUCCESS: 'PERMISSION_202',
  PERMISSION_DELETE_SUCCESS: 'PERMISSION_203',
} as const;

export type PermissionCodeType = (typeof PermissionCode)[keyof typeof PermissionCode];